### ISSUE TITLE
site status vocab needs expanding to include sub-status

### ISSUE THREAD

**Issue by geoderekh** [geological-survey-of-queensland/vocabularies#111]
@geoderekh  @KellyVance The vocab needs to be expanded to include site status and sub-status to account for changes to the DB model. Possibly could use collections like mine status (status), exploration status (sub-status).  
@DavidCrosswellGSQ can you confirm that status and sub-status will be handled in the same vocabulary? If so I'll make the changes.

**Comment by DavidCrosswellGSQ** [comment]
@geoderekh If the sub-statuses are narrower terms of the status, then it is the one vocabulary.

**Comment by geoderekh** [comment]
@DavidCrosswellGSQ  We introduced "Sub-status" for MINOCC to handle exploration status, while "status" would handle the mine status. Should I therefore add the various mine statuses to the site-status vocab and create a new "sub-status" vocab containing just the exploration statuses?

**Comment by KellyVance** [comment]
We may need an extra "on-hold" top concept, but if we do that I see a way we can hierarchy as far down the rabbit hole as we need.

Just an example of one possibility (not saying this is exactly how it should be):

- ststs:abandoned,
- ststs:active,
            -  ststs:exploration
            -  ststs:construction
            -  ststs:extraction (aka mining, aka operating, aka development, etc)
- ststs:on-hold (aka care and maintenance) 
- ststs:rehabilitation
- ststs:never-used,
- ststs:proposed,
- ststs:unknown ;

**Comment by geoderekh** [comment]
@KellyVance  We are going to have to revisit this issue and the lifecycle-status vocab model we were attempting to migrate to. We can leverage the work to date but I think there will be problems with the migration and with mine/exploration statuses going forward. We will also want to try and standardise our vocabs with Abandoned Mines as they have much more mine/minocc data than us and interoperability with their systems would be greatly advantageous for some major NEMI projects. 
Please, lets meet up on Monday.
