### ISSUE TITLE
Before Present timescale

### ISSUE THREAD

**Issue by dr-shorthair** [geological-survey-of-queensland/vocabularies#112]
Useful for scientific and archeological work <100,000 years
Datum 1950

https://en.wikipedia.org/wiki/Before_Present

**Comment by KellyVance** [comment]
A sensible addition. 
I have made suggested vocabulary edit and made a pull request to @nicholascar for review.

**Comment by dr-shorthair** [comment]
@KellyVance I notice you closed this before the PR was resolved. That is different to the usual Git flow, which leaves an issue open until it is resolved or rejected. 

To make things easier one of the magic words in the PR and the related issue will then get closed automatically when the PR is processed. See https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by KellyVance** [comment]
@dr-shorthair 
Thanks for the tip. I have reopened this issue and linked the pull request.
