### ISSUE TITLE
Delete: Seismic Survey Method

### ISSUE THREAD

**Issue by KellyVance** [geological-survey-of-queensland/vocabularies#172]
The seismic survey vocabulary is redundant and requires deletion.
Content is not included in a seismic methods collection in the survey-methods vocabulary.

However, the current vocabulary is used in the CKAN seismic form.
We will need to change the CKAN JSON first and prior to deleting this redundant vocab.
Issue to be used as a flag to complete this action as a later date.

**Comment by DavidCrosswellGSQ** [comment]
Have requested LinkDigital to change the SPARQL query to point to the collection http://linked.data.gov.au/def/geological-observation-method/seismic-methods

**Comment by DavidCrosswellGSQ** [comment]
SPARQL query:
PREFIX skos:<http://www.w3.org/2004/02/skos/core#> SELECT ?concept ?prefLabel WHERE{<http://linked.data.gov.au/def/geological-observation-method/seismic-methods> skos:member ?concept. ?concept skos:prefLabel ?prefLabel.}order by ?prefLabel

**Comment by DavidCrosswellGSQ** [comment]
@KellyVance This vocab can now be deleted.
The new CKAN seismic survey form is pulling from http://linked.data.gov.au/def/geological-observation-method/seismic-methods
