### ISSUE TITLE
Rationalise and Consolidate: Survey type, Survey method, Observation type, Observation instrument 

### ISSUE THREAD

**Issue by geoderekh** [geological-survey-of-queensland/vocabularies#188]
We need to fix the vocabs associated with geophysical surveys following the resolution of multi-type surveys into a single survey (with the raw aquired data attached) to cover the acquisition and then multiple observations of different type (with the processed datasets attached). The processsed datasets can also be related to the original survey as additional datasets where their survey 'type' is recorded by their earth science data category.  

E.g. AG surveys are therefore of type:geophysics and method:airborne. There would also be mag, rads, and DEM observations with the grids/images attached. The Mag/RAD/DEM observation metadata could be omitted if it is not of interest and all datasets could be attached to the original AG survey.

The changes required involves substantial expansion of observation instrument to include AG tech specs and seismic source along with the additional concepts from the survey type review. Additional work will be required to transfer detail from survey type to observation type, remove narrower concepts from survey method, understand how/if obs.sample_preparation will be used in Geophysical surveys, workshop how the new understanding of AG surveys is reflected in Seismic, geochem, general field sampling, etc., possibly writing some documentation along the way. 

@CantRoger might be the right person to lead this. I'll raise this as an activity in the standup to prioritise this work.

**Comment by Greenwoodmatthew** [comment]
@geoderekh I dont think we want to separate the data attached to observations or survey based on a raw/processed classification.  I think all data is an observation that relates to the survey.  That observation may be multi-type or that survey may have many types of observations.

For metadata there should be a consistent approach to where it is stored in relation to the datasets in CKAN so i can be used to display the results
