### ISSUE TITLE
Update: gsq-roles.ttl (2 owner concepts)

### ISSUE THREAD

**Issue by DavidCrosswellGSQ** [geological-survey-of-queensland/vocabularies#189]
Hi @KellyVance 
This vocab https://github.com/geological-survey-of-queensland/vocabularies/blob/master/vocabularies/gsq-roles.ttl
has 2 owner concepts.
Can you please fix?
Thanks, DC

**Comment by KellyVance** [comment]
done.
originator prefLabel fixed. From owner to originator
