### ISSUE TITLE
Update VocPrez process with details of how to publish to VocPrezUAT

### ISSUE THREAD

**Issue by lisa-woody** [geological-survey-of-queensland/vocabularies#208]
1. Can you please update the 'How to Create a Vocabulary' process to include the extra steps required to publish to UAT?
2. Can you please also add the URL for UAT VocPrez  (https://vocabs.uat.gsq.digital/vocabulary) so that people don't mistakenly go to https://test.vocabs.gsq.digital/vocabulary/  ?

**Comment by DavidCrosswellGSQ** [comment]
Updating vocabularies is now an automated process, the process is here:
https://github.com/geological-survey-of-queensland/vocabularies/tree/master/scripts
The same process is used for all environments, it is just the configuration file that gets changed per environment.

@lisa-woody - we encourage everyone to edit Github, so please feel free to add the URL for UAT where you see necessary.

**Comment by DavidCrosswellGSQ** [comment]
SRA are the only people who can publish to VocPrez UAT (and other SRA-managed environments Dev, QA)
You can request them to do such by logging a job at https://sra-it.atlassian.net/servicedesk/customer/portal/31
