### ISSUE TITLE
Update Sample material

### ISSUE THREAD

**Issue by SalEdwards01** [geological-survey-of-queensland/vocabularies#211]
please add sandstone, shale and siltstone to the sample material vocab.

**Comment by KellyVance** [comment]
In parallel with this there is a full rock type vocabulary in the pipeline for better specificity where needed.
But for the Sample Material level do you think any other rock types might be needed?

**Comment by SalEdwards01** [comment]
Hi Vance
I think that sandstone and shale definitely need to be pulled out at the higher level, as they have common specific tests done on them. Siltstone, is not as important.
Sandstone (porosity and vertical and horizontal permeability)
Shale (rock-eval pyrolysis, kinetics, chromatography and gas chromatography and mass spectroscopy).

For example: I think to use the term ‘rock’, is a bit vague to describe a sample that will have detailed analyses (gas desorption, gas composition, thermal maturity, TOC etc.) eventually associated with it.

Cheers
Sally
