### ISSUE TITLE
Update Sample Type Vocab

### ISSUE THREAD

**Issue by SalEdwards01** [geological-survey-of-queensland/vocabularies#212]
please add core plug, 
crushed/milled/ ground rock, 
polished block, 
oriented section 
to sample type vocab

**Comment by KellyVance** [comment]
@SalEdwards01 Do the below additions work for you?

Core Plug:  A plug, or sample, taken from a conventional core for analysis. 
Crushed Rock: A sample of rock that has been artificially crushed, milled, or ground.
  aliases: Milled rock, Ground rock
Polished Block: Rock samples are bonded in epoxy and polished as small round blocks for reflected light microscopy.

Do "oriented sections" fit the definition for either of the below sample types? If so i'll add it as an alias, if not can you give me the one line definition that distinguishes it from these?

- oriented-or-orientation-sample | definition "A sample collected as a known reference for the orientation of other samples."
- oriented-sample | definition "Sample collected with orientation recorded for detailed structural geology analysis"

**Comment by SalEdwards01** [comment]
Does  use of “conventional core” in the core plug definition cover lateral cores, side wall cores, re-drills?

Crushed rock definition- great ☺
Polished block definition -great ☺
Both definitions for oriented sample should be included if possible as they are both used – great ☺
Thanks Sal
☺ ☺ ☺

**Comment by SalEdwards01** [comment]
Thanks Vance
All looks great.
Reviewed and  approved
