### ISSUE TITLE
check sample method vocab against sample preparation vocab

### ISSUE THREAD

**Issue by SalEdwards01** [geological-survey-of-queensland/vocabularies#213]
HI Vance and David 

Please check the vocab assigned to the method field under Sample. It does not give us options that we expect to provide information on how the sample was collected (method). Instead, it appears to be information that will come under Observation about what the lab has done to the sample. We were expecting to be able to assign the type of method used to collect the sample (hand sample, jackhammer, sledgehammer,  scrapings, core section, grab sample, dredge, etc), but instead, the list is of lab processes (chelate, aggregate, dessicate, filter etc).

**Comment by KellyVance** [comment]
duplicate #216 
closing and pasting comment there
