### ISSUE TITLE
Sample-method vs sample-preparation-method

### ISSUE THREAD

**Issue by geoderekh** [geological-survey-of-queensland/vocabularies#216]
Hey all, 

1: GeoProps Data Elements v1.3 shows the vocab for sample_method as Sample Method, while v1.8 has sample preparation method here instead (as well as in Observation.Sample_preparation_method). It seems like a mistake to me. Can you confirm if the vocab for sample_method is correct or not?
2: If the former, we will need to add a lot of concepts there. I also wonder if there are issues using the vocab across sample and obs. 
3: If the latter, we will need to create sample-method.ttl and add the concepts mentioned above. 

@Fred-v-G and @SalEdwards01 flagged this and could have input into the vocab content.

**Comment by KellyVance** [comment]
I _think_ the latter. 
sample preparation method should be  linked to observation>preparation
for sample>method we will need a sample-method.ttl created.

Just need to know what terms people expect to see in such a vocabulary and the definitions for those terms.

**Comment by KellyVance** [comment]
from @SalEdwards01 #213 

> "Please check the vocab assigned to the method field under Sample. It does not give us options that we expect to provide information on how the sample was collected (method). Instead, it appears to be information that will come under Observation about what the lab has done to the sample. We were expecting to be able to assign the type of method used to collect the sample (hand sample, jackhammer, sledgehammer, scrapings, core section, grab sample, dredge, etc), but instead, the list is of lab processes (chelate, aggregate, dessicate, filter etc)."

**Comment by Fred-v-G** [comment]
Hi Vance, I'm actually looking for some direction on how to go about this. I am still completely unfamiliar with GitHub and what I can do with the vocabs

**Comment by KellyVance** [comment]
@Fred-v-G 
Hi Fred. At this stage just an excel list of the missing terms (hand sample, jackhammer, sledgehammer, scrapings, core section, grab sample, dredge, etc) and a definition for each. I can take it from there.

**Comment by Fred-v-G** [comment]
Sure Vance

Where is the (existing?) excel spreadsheet? Or do I create it

Cheers


[http://dnrmintranet.lands.resnet.qg/__data/assets/image/0011/166097/qldgov1.png]
Friedrich von Gnielinski
Geoscientist, Mineral Geoscience
Geological Survey of Queensland
Department of Natural Resources, Mines and Energy
________________________________
P: +61 7 3096 6142
E: Friedrich.vongnielinski@dnrme.qld.gov.au<mailto:Friedrich.vongnielinski@dnrme.qld.gov.au>
A: Level 4, 1 William St, Brisbane, QLD 4000

**Comment by KellyVance** [comment]
No existing one yet. If oyu can create one that would be great. List doesn't need to be comprehensive just the things you, sally, et al can readily think of. We can always add more terms once we've got a preliminary list in place.

**Comment by Fred-v-G** [comment]
Ok Will get onto that tomorrow morning

Cheers

Fred

**Comment by KellyVance** [comment]
@geoderekh @SalEdwards01 
I suggest we point SRA to Geoscience Australia's sampling method vocab as a quick fix. It looks like it requires some clean up and possibly some additions to make it fit-for-purpose for GSQ. But it should at least keep the wolves at bay until we can fix it up properly. https://vocabs.ands.org.au/viewById/195
(SPARQL endpoint http://vocabs.ands.org.au/repository/api/sparql/ga_sampling-method_v1-0)

**Comment by geoderekh** [comment]
Closing this isssue: Actions were: Implemented GA's sampling method, and Sally to create the bespoke GSQ one.
