### ISSUE TITLE
Survey Details Type Vocab needs values

### ISSUE THREAD

**Issue by Greenwoodmatthew** [geological-survey-of-queensland/vocabularies#218]
Hi Vance,

I know it is probably on you schedule, but survey details type vocab is dummy at moment.  It will need values so survey details can be added.  Can these be based on collections from types?  i.e. if survey type is geophysics (and method Airborne), the possible lists of detail types is in a set.  Otherwise i guess we list them in logical grouping order. 

@CantRoger and i can make a start on geophysics ones if you like?

**Comment by KellyVance** [comment]
The detail types can be added to as needed within collections. Feel free to make a start on collating the list and we can start the incremental process of building this out.

**Comment by Greenwoodmatthew** [comment]
covered in https://github.com/geological-survey-of-queensland/vocabularies/pull/223 - closing
