### ISSUE TITLE
Update Borehole Status Event Vocab

### ISSUE THREAD

**Issue by BlakePaul** [geological-survey-of-queensland/vocabularies#233]
We need to record the event from PGGD-02 i.e. Notice of Completion, Alteration or Abandonment.

Lets talk further about this.  We can show you on the PGGD forms.

**Comment by KellyVance** [comment]
Hi @BlakePaul and @LizDerrington 

Below are the current terms in the vocabulary for events that change the status of a borehole.
If you can list out what additional events or sub-categories need to be captured i'll do what I can to add them.

**Current contents**
"PGGD-02"
"WRA-05A"
"PGGD-04"
"PGGD-03"
"MMOL-44";
"PA-42"
"PGGD-01" ;
"Petroleum Production Report"
"Manual Update or Creation"@en ;

**Comment by BlakePaul** [comment]
Need to replace the current Status Event Vocab with the following new Status Event vocab.

Definitions for ‘Status Event’ Vocab

Drilling of borehole on notice: A ‘Notice of intention to drill a petroleum well or bore’ Form PGGD-01 has been lodged

Completion: Notice that the initial drilling activities of the borehole have been completed Form PGGD-02 

Alteration: Notice of the activities that occur after completion of the initial drilling activities of the borehole Form PGGD-02 

Abandonment: Notice of when a borehole is shut-in and permanently closed Form PGGD-O2 

Hydraulic fracturing on notice: A ‘Notice of intention to carry out hydraulic fracturing activities’ Form PGGD-O3 has been lodged

Hydraulic fracturing abandoned: The full well frac was cancelled and abandoned.

Completion of hydraulic fracturing: A ‘Notice of completion of hydraulic fracturing activities’ Form PGGD-04 has been lodged

Conversion to water supply borehole on notice: A ‘Notice of intention to convert a petroleum well to a water observation bore or water supply bore’ Form PA- 42 has been lodged

Conversion to water supply borehole: A ‘Notice of completion of conversion of petroleum well to water supply bore or water observation bore’ Form WRA-05A has been lodged

Conversion to water observation borehole on notice: A ‘Notice of intention to convert a petroleum well to a water observation bore or water supply bore’ Form PA-42 has been lodged

Conversion to water observation borehole: A ‘Notice of completion of conversion of petroleum well to water supply bore or water observation bore’ Form WRA-05A has been lodged

Decommissioning: A ‘Notice of decommissioning a well, water observation bore, water monitoring bore or water supply bore’ Form MMOL-44 has been lodged. ‘Decommissioning’ refers to the act of permanently shutting- in and abandoning a borehole.

Petroleum Production Report: A Petroleum Production Report as defined under Section 42 of the Petroleum and Gas (General Provisions) Regulation 2017

Manual Update or Creation: Manually update an existing borehole status or manually create a new borehole status

**Comment by KellyVance** [comment]
@DavidCrosswellGSQ I support Paul's proposal. It makes sense to separate the forms submitted (already captured in the report types), with the actual event that occurs.
Can you please comment on if you can think of any unintended consquences?
If you support the change I'll start making the required edits.

**Comment by LizDerrington** [comment]
I also support the proposal.

**Comment by KellyVance** [comment]
@BlakePaul and @LizDerrington 

Can you please confirm that your proposed changes reflect [the future state business processes](https://github.com/geological-survey-of-queensland/gsq-lodgement-portal/blob/master/PGGD-forms-README.MD#future-state-business-process)?
Can you also please add to the definitions to include how each event type affects the borehole status and/or type, or if the event is a recording of a reportable activity that does not change the status.

**Comment by KellyVance** [comment]
Addressed and fixed in #267
