### ISSUE TITLE
Need to add an appropriate role/s for observation agent

### ISSUE THREAD

**Issue by geoderekh** [geological-survey-of-queensland/vocabularies#243]
P.I.s and observers are not the same thing. 
Even the definition says nothing about a party who observes. 
The altLabel facilitates a suggestion to use PI as the observation agent, which is wrong. the act of observing is independent of research and it needs to be pulled out as its own concept. 

_Originally posted by @geoderekh in https://github.com/geological-survey-of-queensland/vocabularies/pull/239_

**Comment by KellyVance** [comment]
Closest match in existing source vocabularies is
```
datac:DataCollector a skos:Concept ;
    skos:definition "Person/institution responsible for finding, gathering/collecting data under the guidelines of the author(s) or Principal Investigator (PI)."@en ;
    skos:inScheme <http://linked.data.gov.au/def/dataciteroles> ;
    skos:prefLabel "Data Collector"@en ;
    skos:scopeNote "May also use when crediting survey conductors, interviewers, event or condition observers, person responsible for monitoring key instrument data."@en ;
    skos:topConceptOf <http://linked.data.gov.au/def/dataciteroles> .
```
Let me know if this fits the requirement (with addition of an observor altLabel). If so I can introduce this to the gsq-roles vocabulary.
Otherwise please advise a more suitable defintion so i can generate a bespoke GSQ concept.

**Comment by Greenwoodmatthew** [comment]
There may be some conflicts here in terms of what to apply.  E.g. in a geophysical work setting the data collection (and observation i guess) is done by a contractor.  So should the role contractor, or data collector be used?  I see the vocab has a skos:scopenote that we could define the standards in.   Which particular case example are you thinking of Derek?  An observer like D Hoy?  Or like ALS Geochem?

**Comment by KellyVance** [comment]
There is a slight disjoint. 
There are functional roles here: Principle investigator, data collector, driller, submitter, owner, processor etc
Then there are responsibility/accountability roles: operator vs contractor.

e.g. a driller could be the operating company or a contractor. Where, in the context of the permit or mine we care who the operator is, but in the context of the specific borehole we care who drilled the thing regardless of whether they were contracted to do it or did it on their own project.

We could split this into two vocabularies and two concept schemes. Or create two collections to leverage to help display the right bundle of terms in the right context. The latter is easier and I dont think breaks anything.

**Comment by Greenwoodmatthew** [comment]
Thanks @KellyVance i think we are mostly on the same wavelength on this.  The bigger question is what we *should* be storing in database and how we can make the method and nomenclature homogeneous across the system

For an AG survey i want to know the client (owner) who commissioned the survey, the company who flew the survey (contractor/data collector) same for most other geophysical work.   The contractor in this case is like the 'driller' role in BH.  A specialist who performed the specialised task

**Comment by geoderekh** [comment]
The question that sparked this was what role to put against an observation agent that determines a site has a MINOCC observation? 
Both Principal Investigator and Data Collector seem to fit into a heirarchy that would be present in any large project. In the instance we are talking about, data collector fits better. Even if someone was collecting data for a project where they were also the PI, their role in observing the MINOCC and other miscellaneous field observations would be that of a data collector, with the PI role restricted to higher-level project managemnt activities (perhaps if they organised the field survey they would be the PI for the survey and a data collector for the samples and obs collected therein)

@Greenwoodmatthew and @KellyVance let us resolve this issue by adding DataCollector to the vocab to facilitate the SG mapping (i will notify SRA of the role to assign for minocc). 
Of less urgency is the issue of survey agents, so lets address that one out of github in a session next week (by which time it will probably be urgent lol)

**Comment by geoderekh** [comment]
I see data collector is in the vocab already so closing this one out.
