### ISSUE TITLE
I like the thing that Derek Did

### ISSUE THREAD

**Issue by KellyVance** [geological-survey-of-queensland/vocabularies#251]
### Because It was good

> Things

 here because it needs **more** _words_

[There is an image here](https://earthview.withgoogle.com/fderik-mauritania-6366)
@geoderekh @LizDerrington

**Comment by geoderekh** [comment]
i like it too. Isn't it the best!

**Comment by KellyVance** [comment]
Cool! This was a test.

**Comment by KellyVance** [comment]
opened and closed again
