### ISSUE TITLE
Additions to improve geounits vocab

### ISSUE THREAD

**Issue by SalEdwards01** [geological-survey-of-queensland/vocabularies#256]
Hi Vance  
Please add the following units from Merlin to the geounits vocab. 
[Missing Analysis Result units.xlsx](https://github.com/geological-survey-of-queensland/vocabularies/files/4756182/Missing.Analysis.Result.units.xlsx)

Any questions please go to Mike.
Thanks, Mike and Sal

**Comment by mckillopm** [comment]
File can be found G:\Geological_Survey\Energy\Sally GDMP files\Missing Analysis Result units.xlsx
We were unable to upload.
Mike

**Comment by KellyVance** [comment]
@SalEdwards01 and @mckillopm I have made file changes and put in pull request #257 
As this is a slightly more complex process I will let Nick review, approve and merge, then get you to review the results in the end user interface.
