### ISSUE TITLE
Georesources Report Types vocab- PrefLabel Notice forms.

### ISSUE THREAD

**Issue by LukeHauck** [geological-survey-of-queensland/vocabularies#266]
The Lodgement Portal is using the PrefLabel for the Notice forms, e.g. _Notice of Intention to carry out seismic survey or scientific or technical survey_

These PrefLabels fall under the concept of the form ID. e.g. _PA-21A_

As an improvement to Lodge Portal, it was suggested that the form ID be included in the drop-down list of reports to lodge alongside the title of the form. e.g. _PA-21A Notice of Intention to carry out seismic survey or scientific or technical survey_

Will this require a vocab change?
If so, could the PrefLabel for the Notice Forms be updated to include the Form ID.

**Comment by KellyVance** [comment]
Seems like a good idea. Label changes are fairly straight forward.
Can also address the following issue from @GSQ-AI in the same Pull Request.

> At the same time, can we make some changes to line 270 to change "Mine Plan Lodgement" to "Mine Working Plan", based on some input from Genevieve Evans regarding their naming?

**Comment by LukeHauck** [comment]
Good idea to include that too. Quickest way to resolve this from here?

**Comment by KellyVance** [comment]
Once we get the ok for the Mine Plan Lodgement name change I'll put both edits in a PR and fire it through.
