### ISSUE TITLE
where is the lithology vocabulary?

### ISSUE THREAD

**Issue by smrgeoinfo** [geological-survey-of-queensland/vocabularies#273]
I'm trying to find the vocabulary referenced in https://github.com/geological-survey-of-queensland/vocabularies/pull/205 , but can't find it. I'd like to take a look and see how it fits with GIC and other lithology vocabs I'm workign with...

**Comment by KellyVance** [comment]
The lithology vocabulary pull request has been temporarily removed for some ttl format remediation.
It is being put through a process to improve interoperability and validate some skos rules that were omitted in the initial build.
We will re-submit a pull request to go through our approval process in the near future in conjunction with a mineral vocabulary.

**Comment by smrgeoinfo** [comment]
Thanks.  I'd be very interested in seeing the Lith vocabulary as soon as you're ready to share-- I"m working on ontology for the Loop3D project. Currently we've incorporated CGI Simple lithology, with a couple extensions for massive sulphide and altered rocks.

**Comment by nicholascar** [comment]
Likely of interest:

* CGI's Simple Lithology, as delivered by a test VocPrez server: 
     * http://cgi.surroundaustralia.com/vocabulary/simplelithology/
* GA's Lithology Qualifiers, another VocPrez test server:
    * http://ga.surroundaustralia.com/vocabulary/Lithology_Qualifiers/

**Comment by smrgeoinfo** [comment]
@nicholascar I like VocPrez-- first time I've seen it.  Nice for the simple lith vocab.  
The lith qualifiers vocab is kind of scary-- convolves all kinds of different properties that in GeoSciML and the GKO ontology are represented in different ways....

**Comment by bluetyson** [comment]
Stephen, I have been using Loop a bit.  An ontology project sounds interesting.

Nicholas, also, thank you!

Vance, this is all looking really good, too.

**Comment by KellyVance** [comment]
https://github.com/geological-survey-of-queensland/vocabularies/blob/master/vocabularies/lithology.ttl

This is a rock type + vocabulary. i.e. it includes some common lithological logging observation types that are not rock types unto themselves e.g. core loss
