### ISSUE TITLE
Party Identifier type vocab has missing terms and should be renamed

### ISSUE THREAD

**Issue by geoderekh** [geological-survey-of-queensland/vocabularies#328]
The file identifier-type.ttl corresponds to http://vocabs.gsq.digital/vocabulary/party-identifier-type and should be renamed "party-identifier-type.ttl" for clarity. 

Also (and more importantly), we need to create 4 new concepts for operator codes and client numbers from MERLIN, GEM, and MMOL to address 2 data migration bugs.  

The 4 preLabels are: Operator Code, MMOL Client ID, Merlin Client No, GEM Party ID. Descriptions should be self evident. 

No clear Content Authority/vocab owner for party vocabs so assigning issue to @johnmckellar as Vocab Data Manager and @DavidArmstrongGSQ as the Geoprops data manager to coordinate resolution. 

FYI @AdrianStead this work covers the GSQ work for GDT-473 and the new bug in Unresolved_MVP_bugs.xlsx

**Comment by johnmckellar** [comment]
Operator Code does not need to be brought into a vocab, and MMOL Client ID, Merlin Client No & GEM Party ID are to be deferred, as their respective IDs need to be better delimited, apart from UN. The identified vocab is at best unsuitable for this.
