### ISSUE TITLE
Additions to GSQ Alias

### ISSUE THREAD

**Issue by broughd-qld** [geological-survey-of-queensland/vocabularies#341]
For DES to use the Catalogue, we need to create a list of our organisation and org units. These critically link to publishers in the metadata schema.

@DavidCrosswellGSQ @KellyVance I'm proposing to add items and refine the [GSQ Alias](https://github.com/geological-survey-of-queensland/vocabularies/blob/master/vocabularies/gsq-alias.ttl) file to  include this information and build out some of the ORG ontology items.
cc @UbuntuScott

**Comment by KellyVance** [comment]
All, this might best be done by changing the vocabulary title here to simply Alias or Queensland Government Alias and then creating gsq-alias and des-alias collections to suit the specific needs of each. This would also future-proof us should any other departments wish to join the fun later on. Thoughts?

**Comment by broughd-qld** [comment]
Opening up the terms to future use would be good. Our initial thoughts on what our structure could look like followed much of the ORG ontology - example below. But potentially we overthought some of it though!
Using ORG means we can morph items over time, using a structured language - which helps with changes to organisations and names.

###  https://linked.data.qld.gov.au/agent/DES
:DES rdf:type owl:NamedIndividual ,
              org:FormalOrganization ,
              prov:Organization ;
     org:hasPrimarySite :GeorgeSt ;
     org:hasSite :Ecosciences ;
     rdfs:label "Department of Environment and Science" .

###  https://linked.data.qld.gov.au/agent/DES-10157
:DES-10157 rdf:type owl:NamedIndividual ,
                    org:OrganizationalUnit ;
           org:hasSite :Ecosciences ;
           org:unitOf :DES ;
           rdfs:label "Science and Technology" ,
                      "Science and Technology Division" .


###  https://linked.data.qld.gov.au/agent/Ecosciences
:Ecosciences rdf:type owl:NamedIndividual ,
                      org:Site ;
             org:siteAddress <http://linked.data.gov.au/dataset/gnaf-2016-05/address/GAQLD163292916> ,
                             [ rdf:type vcard:Address ;
                               vcard:country-name "Australia" ;
                               vcard:locality "Dutton Park" ;
                               vcard:postal-code "4102" ;
                               vcard:region "QLD" ;
                               vcard:street-address "41 Boggo Road"
                             ] ;
             rdfs:label "Ecosciences Precinct" .

###  https://linked.data.qld.gov.au/agent/GeorgeSt
:GeorgeSt rdf:type owl:NamedIndividual ,
                   org:Site ;
          org:siteAddress <http://linked.data.gov.au/dataset/gnaf-2016-05/address/GAQLD163137756> ,
                          [ rdf:type vcard:Address ;
                            vcard:country-name "Australia" ;
                            vcard:locality "Brisbane" ;
                            vcard:postal-code "4001" ;
                            vcard:region "QLD" ;
                            vcard:street-address "400 George Street"
                          ] ;
          rdfs:label "400 George Street, Brisbane" .

**Comment by KellyVance** [comment]
Our alias vocabulary is really just for defining the source of secondary names for data objects and entries, so it might be a bit rudimentary and overly specific for your purposes.

For our full list of organisations and their relationships we have a Party Database component in our data structure https://github.com/geological-survey-of-queensland/gsq-party-profile

But for an Ontology based approach, we could take what you have above and define a new Queensland Government Organisation ontology that we could expand over time.

**Comment by broughd-qld** [comment]
@KellyVance based on the above, would you like me to create a new ontology based for organisations (ie agencies, org units, locations) or add them to gsq_alias?
Recognising that full details for GSQ will be kept in the Party Database and DES will likely have additional details for internal use?
I'm leaning towards a fresh approach as we can design for expansion over time with other agencies.

**Comment by KellyVance** [comment]
@broughd-qld I tend to agree that a fresh approach is best too. It might be pushing this vocabulary beyond its true intent and essence to expand it to a full ontology. That said, this alias list, would be one element feeding into a larger structure to deal with organisation records.

**Comment by broughd-qld** [comment]
OK - I'll start a fresh ontology. Will be easier to merge and relate than disentangle at a later date.

**Comment by broughd-qld** [comment]
@KellyVance as we discussed yesterday the ontology approach and the party database are probably complementary and will serve different purposes. I'll kick off a QG agency ontology and we can expand as required, noting that full details should be in the party database or other systems as needed.
