### ISSUE TITLE
Additions to Unit of Measure vocabulary

### ISSUE THREAD

**Issue by broughd-qld** [geological-survey-of-queensland/vocabularies#379]
Hi @nicholascar and @KellyVance 
We need to create a collection for units of measure that is used by DES for our catalogue. At the moment, we are focussed on only using items from QUDT.

Should we augment the [geounits](https://github.com/geological-survey-of-queensland/vocabularies/blob/master/vocabularies/geounits.ttl) vocabulary with the UoM that we need and then create a collection? Will this cause issues for the GSQ data portal?

Advice appreciated please.

cc @UbuntuScott

**Comment by nicholascar** [comment]
If you need a smaller set of QUDT UoM than the geo units, there’s no reason you can’t just make yet another vocabulary, as long as you are re-using the QUDT URIs. This other vocab would just yet another profile/subset of QUDT but tailored for your needs.

You can even add custom annotations to the concepts of you really need to, as long as you don’t co trading any QUDT properties.

**Comment by broughd-qld** [comment]
Thanks for the advice. Will create a new vocab, which will let us use the terms we need and not impact on the geounits one.
