### ISSUE TITLE
obstyp:positional has wrong def

### ISSUE THREAD

**Issue by geoderekh** [geological-survey-of-queensland/vocabularies#456]
https://github.com/geological-survey-of-queensland/vocabularies/blob/530c121818c68c48a7305b459a39b11fb762a2d0/vocabularies-gsq/geological-observation-type.ttl#L418

**Comment by geoderekh** [comment]
still an issue

**Comment by Greenwoodmatthew** [comment]
Agree, this is a copy of the physical property obs def.  

an we make a pull request to update?

**Comment by GSQ-AI** [comment]
Yeah, as simple as making a branch, edit the vocab and pull request to commit.
Did you have a definition for positional obs already? 

Pulling one out of nothing, if you don't:
"An observation of the relative spatial properties of a physical object or location, from a known datum point such as the Euclidean distance from the known position of the observer to another point."@en ;

**Comment by geoderekh** [comment]
Closing issues as was fixed by pull 522.
