### ISSUE TITLE
Updated vocabs not being pushed to Geoprops as they should be

### ISSUE THREAD

**Issue by geoderekh** [geological-survey-of-queensland/vocabularies#506]
I notice that geoproperties PROD still recognises Hyperspectral Scan as a valid sample type despite it recently being deleted from the vocabulary. The commit in the vocab patch branch has been merged to master, so it seems that either Prez and/or the Geoprops server have not been refreshed. 

This issue seems to pop up quite regularly, telling me that the procedure either isn't being followed or that it doesn't exist. 

How can we better align the vocab PR-commit-merge procedure (seems to be working fine) with the last two steps to update the graph DB/Prez (I thought Edmond automated this recently, no?) and then the SRA service request to refresh the Geoprops server (manual step I think).

**Comment by Steven-Bowden** [comment]
Moved to GSD-480 for resolution
