### ISSUE TITLE
Spatial Region Vocabulary

### ISSUE THREAD

**Issue by KellyVance** [geological-survey-of-queensland/vocabularies#6]
@DavidCrosswellGSQ 
@nicholascar 

What is the purpose of this vocabulary?
Can we not automatically determine this from associated spatial objects? Is it a derived descriptor only? Or it it intended as a primary search feature?
Also I would use standard GIS terminology i.e. point, line/polyline, polygon for our preferred labels. If the current names are from an international standard I would keep them as an alternate label so they can still be references, but this is not the language geologists and GIS people converse in so it would have limited use.

**Comment by nicholascar** [comment]
@KellyVance This vocab is a generic spatial dimentionalies indicator only. There were some fields in GeoSciML and some of the GSQ data systems for "2D", "3D" etc., I think mainly for seismic surveys and that sort of thing. To head off having multiple models with their own trivial vocabs of 2D, 3D etc., I brought this one it. So, if anyone ever just needs to indicate 1 - 3D anywhere, they can use this.

It could be used for search but likely as a facet within an already faceted search like "2D" within "seismic survey" to not get "3D" results within that facet..

There's really a very different set of use cases for recording something like dimensionality in a vocab object (categorisation/classification) from dealing with geometries. If it's important to differentiate 2D v. 3D in some sot of objects, like seismic surveys, then you tag accordingly, perhaps with this vocab. Actually doing something like intersections or area projections with  point/polygon/line data, which you would store in the appropriate objects, isn't really a task for catalogue-level metadata, other than simple bounding box searches perhaps.

**Comment by KellyVance** [comment]
@nicholascar Spatial region implies a GIS function to define a region rather than dimensionality of a dataset. I think to clarify intent and to not potentially be conflated with other common geological and spatial concepts the name of the vocabulary may need revision.

**Comment by nicholascar** [comment]
@KellyVance sure we can rename. The name used here is taken from the class name of the objects in the Basic Formal Ontology, so I wasn’t making anything up, but I agree we can probably make things clearer.
